version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: .Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://raptaiuser:raptaipassword@db:5432/raptaidb
      - DB_FORCE_ROLL_BACK=False
      - PROJECT_NAME=raptai-pro
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=raptaiuser
      - POSTGRES_PASSWORD=raptaipassword
      - POSTGRES_DB=raptaidb
    ports:
      - "5432:5432"

volumes:
  postgres_data:
