version: "3.8"

services:
  rag-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
    restart: unless-stopped
